language: scala
sudo: required
dist: precise
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.cache/pip
    - $HOME/.pip-cache
    - $HOME/.sbt/launchers
    - /tmp/kafka-bin
jdk:
  - oraclejdk8
scala:
   - 2.11.8
sudo: false
addons:
  apt:
    packages:
      - axel
before_install:
  - pip install --user virtualenv
  - virtualenv myenv
  - source myenv/bin/activate
  - export PATH=myenv/bin/:$PATH
  - pip install --upgrade pip
  - pip install --upgrade coverage
  - pip install nose codecov unittest2
  - pip install pep8 pylint sphinx tox testinstances
script:
  - ./build/sbt scalastyle
  - "pep8 --ignore=E402 kafka_streams_python_cthulhu/"
  - ./build/sbt clean coverage compile test coverageReport
  - bash <(curl -s https://codecov.io/bash) -cF scala || echo "No Scala report uploaded"
  - nosetests --logging-level=INFO --detailed-errors --verbosity=2 --with-coverage --cover-html-dir=./htmlcov --cover-package=kafka_streams_python_cthulhu --with-doctest --doctest-options=+ELLIPSIS
  - bash <(curl -s https://codecov.io/bash) -cF python || echo "No Python report uploaded"
notifications:
  email:
    recipients:
      - holden@pigscanfly.ca
addons:
  apt:
    packages:
    - libev-dev
    - libsnappy-dev
    - zlib1g-dev  # for librdkafka